### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ZorvShadow** [halfuwu/FortniteAutoExporter#13]
```
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at me.fungames.jfortniteparse.ue4.reader.FByteArchive.setPos(FByteArchive.kt:20)
        at me.fungames.jfortniteparse.ue4.reader.FByteArchive.seek(FByteArchive.kt:31)
        at me.fungames.jfortniteparse.ue4.pak.objects.FPakInfo$Companion.readPakInfo(FPakInfo.kt:42)
        at me.fungames.jfortniteparse.ue4.pak.PakFileReader.<init>(PakFileReader.kt:48)
        at me.fungames.jfortniteparse.ue4.pak.PakFileReader.<init>(PakFileReader.kt:37)
        at me.fungames.jfortniteparse.ue4.pak.PakFileReader.<init>(PakFileReader.kt:38)
        at me.fungames.jfortniteparse.fileprovider.DefaultFileProvider.scanFiles(DefaultFileProvider.kt:48)
        at me.fungames.jfortniteparse.fileprovider.DefaultFileProvider.<init>(DefaultFileProvider.kt:32)
        at me.fungames.jfortniteparse.fileprovider.DefaultFileProvider.<init>(DefaultFileProvider.kt:28)
        at me.fungames.jfortniteparse.fileprovider.DefaultFileProvider.<init>(DefaultFileProvider.kt)
        at com.halfheart.fortniteautoexporter.Main.main(Main.java:69)
```

**Comment by ZorvShadow** [comment]
how do i close, i found the answer
