### ISSUE TITLE
Error when trying to export skin: "Tony Stark"

### ISSUE THREAD

**Issue by DjordyKoert** [halfuwu/FortniteAutoExporter#2]
Last lines from console:
```
[JFortniteParse] INFO: Successfully parsed package : FortniteGame/Content/Athena/Items/Cosmetics/Characters/CID_843_Athena_Commando_M_HightowerTomato_Casual.uasset
java.lang.NullPointerException
        at com.halfheart.fortniteautoexporter.Main.skinToParts(Main.java:199)
        at com.halfheart.fortniteautoexporter.Main.selectSkinPrompt(Main.java:139)
        at com.halfheart.fortniteautoexporter.Main.main(Main.java:77)
```

**Comment by halfuwu** [comment]
Will look into this.

**Comment by halfuwu** [comment]
Yeah I've got no clue as to why this is happening, same thing goes for Thor.

The errors are mainly coming from JFortniteParse so there's not much I can do about that.

**Comment by halfuwu** [comment]
Works in the latest update
